package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AsigConsultorio generated by hbm2java
 */
@Entity
@Table(name="asig_consultorio"
    ,catalog="hospitalbd"
)
public class AsigConsultorio  implements java.io.Serializable {


     private Integer idAsigConsultorio;
     private Consultorios consultorios;
     private Registros registros;
     private Date fecha;

    public AsigConsultorio() {
    }

    public AsigConsultorio(Consultorios consultorios, Registros registros, Date fecha) {
       this.consultorios = consultorios;
       this.registros = registros;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_asig_consultorio", unique=true, nullable=false)
    public Integer getIdAsigConsultorio() {
        return this.idAsigConsultorio;
    }
    
    public void setIdAsigConsultorio(Integer idAsigConsultorio) {
        this.idAsigConsultorio = idAsigConsultorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consultorio", nullable=false)
    public Consultorios getConsultorios() {
        return this.consultorios;
    }
    
    public void setConsultorios(Consultorios consultorios) {
        this.consultorios = consultorios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_registro", nullable=false)
    public Registros getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Registros registros) {
        this.registros = registros;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


