package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsigDocumentos generated by hbm2java
 */
@Entity
@Table(name="asig_documentos"
    ,catalog="hospitalbd"
)
public class AsigDocumentos  implements java.io.Serializable {


     private Integer idAsigDocu;
     private Registros registros;
     private TiposDocumentos tiposDocumentos;
     private String numeroDocu;

    public AsigDocumentos() {
    }

    public AsigDocumentos(Registros registros, TiposDocumentos tiposDocumentos, String numeroDocu) {
       this.registros = registros;
       this.tiposDocumentos = tiposDocumentos;
       this.numeroDocu = numeroDocu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_asig_docu", unique=true, nullable=false)
    public Integer getIdAsigDocu() {
        return this.idAsigDocu;
    }
    
    public void setIdAsigDocu(Integer idAsigDocu) {
        this.idAsigDocu = idAsigDocu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_registro", nullable=false)
    public Registros getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Registros registros) {
        this.registros = registros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_docu", nullable=false)
    public TiposDocumentos getTiposDocumentos() {
        return this.tiposDocumentos;
    }
    
    public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
        this.tiposDocumentos = tiposDocumentos;
    }

    
    @Column(name="numero_docu", nullable=false, length=15)
    public String getNumeroDocu() {
        return this.numeroDocu;
    }
    
    public void setNumeroDocu(String numeroDocu) {
        this.numeroDocu = numeroDocu;
    }




}


