package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AsigTurnos generated by hbm2java
 */
@Entity
@Table(name="asig_turnos"
    ,catalog="hospitalbd"
)
public class AsigTurnos  implements java.io.Serializable {


     private Integer idAsigTurno;
     private DiasTurnos diasTurnos;
     private Horarios horarios;
     private Registros registros;
     private String mesAnio;
     private char estado;
     private Set<Asistencias> asistenciases = new HashSet<Asistencias>(0);

    public AsigTurnos() {
    }

	
    public AsigTurnos(DiasTurnos diasTurnos, Horarios horarios, Registros registros, String mesAnio, char estado) {
        this.diasTurnos = diasTurnos;
        this.horarios = horarios;
        this.registros = registros;
        this.mesAnio = mesAnio;
        this.estado = estado;
    }
    public AsigTurnos(DiasTurnos diasTurnos, Horarios horarios, Registros registros, String mesAnio, char estado, Set<Asistencias> asistenciases) {
       this.diasTurnos = diasTurnos;
       this.horarios = horarios;
       this.registros = registros;
       this.mesAnio = mesAnio;
       this.estado = estado;
       this.asistenciases = asistenciases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_asig_turno", unique=true, nullable=false)
    public Integer getIdAsigTurno() {
        return this.idAsigTurno;
    }
    
    public void setIdAsigTurno(Integer idAsigTurno) {
        this.idAsigTurno = idAsigTurno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_dia", nullable=false)
    public DiasTurnos getDiasTurnos() {
        return this.diasTurnos;
    }
    
    public void setDiasTurnos(DiasTurnos diasTurnos) {
        this.diasTurnos = diasTurnos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_horario", nullable=false)
    public Horarios getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Horarios horarios) {
        this.horarios = horarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_registro", nullable=false)
    public Registros getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Registros registros) {
        this.registros = registros;
    }

    
    @Column(name="mes_anio", nullable=false, length=8)
    public String getMesAnio() {
        return this.mesAnio;
    }
    
    public void setMesAnio(String mesAnio) {
        this.mesAnio = mesAnio;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asigTurnos")
    public Set<Asistencias> getAsistenciases() {
        return this.asistenciases;
    }
    
    public void setAsistenciases(Set<Asistencias> asistenciases) {
        this.asistenciases = asistenciases;
    }




}


