package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsigEspecialidad generated by hbm2java
 */
@Entity
@Table(name="asig_especialidad"
    ,catalog="hospitalbd"
)
public class AsigEspecialidad  implements java.io.Serializable {


     private Integer idAsigEspecialidad;
     private Especialidades especialidades;
     private Registros registros;

    public AsigEspecialidad() {
    }

    public AsigEspecialidad(Especialidades especialidades, Registros registros) {
       this.especialidades = especialidades;
       this.registros = registros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_asig_especialidad", unique=true, nullable=false)
    public Integer getIdAsigEspecialidad() {
        return this.idAsigEspecialidad;
    }
    
    public void setIdAsigEspecialidad(Integer idAsigEspecialidad) {
        this.idAsigEspecialidad = idAsigEspecialidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_especialidad", nullable=false)
    public Especialidades getEspecialidades() {
        return this.especialidades;
    }
    
    public void setEspecialidades(Especialidades especialidades) {
        this.especialidades = especialidades;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_registro", nullable=false)
    public Registros getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Registros registros) {
        this.registros = registros;
    }




}


