package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asistencias generated by hbm2java
 */
@Entity
@Table(name="asistencias"
    ,catalog="hospitalbd"
)
public class Asistencias  implements java.io.Serializable {


     private Integer idAsistencia;
     private AsigTurnos asigTurnos;
     private Usuarios usuarios;
     private Date horaLlegada;
     private Date horaSalida;
     private char estado;

    public Asistencias() {
    }

    public Asistencias(AsigTurnos asigTurnos, Usuarios usuarios, Date horaLlegada, Date horaSalida, char estado) {
       this.asigTurnos = asigTurnos;
       this.usuarios = usuarios;
       this.horaLlegada = horaLlegada;
       this.horaSalida = horaSalida;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_asistencia", unique=true, nullable=false)
    public Integer getIdAsistencia() {
        return this.idAsistencia;
    }
    
    public void setIdAsistencia(Integer idAsistencia) {
        this.idAsistencia = idAsistencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_turno", nullable=false)
    public AsigTurnos getAsigTurnos() {
        return this.asigTurnos;
    }
    
    public void setAsigTurnos(AsigTurnos asigTurnos) {
        this.asigTurnos = asigTurnos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="hora_llegada", nullable=false, length=19)
    public Date getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Date horaLlegada) {
        this.horaLlegada = horaLlegada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="hora_salida", nullable=false, length=19)
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


