package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Consultorios generated by hbm2java
 */
@Entity
@Table(name="consultorios"
    ,catalog="hospitalbd"
)
public class Consultorios  implements java.io.Serializable {


     private Integer idConsultorio;
     private Set<AsigConsultorio> asigConsultorios = new HashSet<AsigConsultorio>(0);

    public Consultorios() {
    }

    public Consultorios(Set<AsigConsultorio> asigConsultorios) {
       this.asigConsultorios = asigConsultorios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_consultorio", unique=true, nullable=false)
    public Integer getIdConsultorio() {
        return this.idConsultorio;
    }
    
    public void setIdConsultorio(Integer idConsultorio) {
        this.idConsultorio = idConsultorio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consultorios")
    public Set<AsigConsultorio> getAsigConsultorios() {
        return this.asigConsultorios;
    }
    
    public void setAsigConsultorios(Set<AsigConsultorio> asigConsultorios) {
        this.asigConsultorios = asigConsultorios;
    }




}


