package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatosPacientes generated by hbm2java
 */
@Entity
@Table(name="datos_pacientes"
    ,catalog="hospitalbd"
)
public class DatosPacientes  implements java.io.Serializable {


     private Integer idPaciente;
     private String duiPaciente;
     private String nombre;
     private String apellido;
     private String edad;
     private String fechaNacimiento;
     private String direccion;
     private int nacionalidad;
     private String telefono;
     private int idEncargado;
     private Set<RecetasPacientes> recetasPacienteses = new HashSet<RecetasPacientes>(0);
     private Set<Citas> citases = new HashSet<Citas>(0);
     private Set<ExamenesPacientes> examenesPacienteses = new HashSet<ExamenesPacientes>(0);

    public DatosPacientes() {
    }

	
    public DatosPacientes(String duiPaciente, String nombre, String apellido, String edad, String fechaNacimiento, String direccion, int nacionalidad, String telefono, int idEncargado) {
        this.duiPaciente = duiPaciente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.edad = edad;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.nacionalidad = nacionalidad;
        this.telefono = telefono;
        this.idEncargado = idEncargado;
    }
    public DatosPacientes(String duiPaciente, String nombre, String apellido, String edad, String fechaNacimiento, String direccion, int nacionalidad, String telefono, int idEncargado, Set<RecetasPacientes> recetasPacienteses, Set<Citas> citases, Set<ExamenesPacientes> examenesPacienteses) {
       this.duiPaciente = duiPaciente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.nacionalidad = nacionalidad;
       this.telefono = telefono;
       this.idEncargado = idEncargado;
       this.recetasPacienteses = recetasPacienteses;
       this.citases = citases;
       this.examenesPacienteses = examenesPacienteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_paciente", unique=true, nullable=false)
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="dui_paciente", nullable=false, length=10)
    public String getDuiPaciente() {
        return this.duiPaciente;
    }
    
    public void setDuiPaciente(String duiPaciente) {
        this.duiPaciente = duiPaciente;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=50)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="edad", nullable=false, length=2)
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }

    
    @Column(name="fecha_nacimiento", nullable=false, length=15)
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="direccion", nullable=false)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="nacionalidad", nullable=false)
    public int getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(int nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="telefono", nullable=false, length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="id_encargado", nullable=false)
    public int getIdEncargado() {
        return this.idEncargado;
    }
    
    public void setIdEncargado(int idEncargado) {
        this.idEncargado = idEncargado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datosPacientes")
    public Set<RecetasPacientes> getRecetasPacienteses() {
        return this.recetasPacienteses;
    }
    
    public void setRecetasPacienteses(Set<RecetasPacientes> recetasPacienteses) {
        this.recetasPacienteses = recetasPacienteses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datosPacientes")
    public Set<Citas> getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set<Citas> citases) {
        this.citases = citases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datosPacientes")
    public Set<ExamenesPacientes> getExamenesPacienteses() {
        return this.examenesPacienteses;
    }
    
    public void setExamenesPacienteses(Set<ExamenesPacientes> examenesPacienteses) {
        this.examenesPacienteses = examenesPacienteses;
    }




}


