package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DiasTurnos generated by hbm2java
 */
@Entity
@Table(name="dias_turnos"
    ,catalog="hospitalbd"
)
public class DiasTurnos  implements java.io.Serializable {


     private Integer idDia;
     private String dia;
     private Set<AsigTurnos> asigTurnoses = new HashSet<AsigTurnos>(0);

    public DiasTurnos() {
    }

	
    public DiasTurnos(String dia) {
        this.dia = dia;
    }
    public DiasTurnos(String dia, Set<AsigTurnos> asigTurnoses) {
       this.dia = dia;
       this.asigTurnoses = asigTurnoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_dia", unique=true, nullable=false)
    public Integer getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(Integer idDia) {
        this.idDia = idDia;
    }

    
    @Column(name="dia", nullable=false, length=10)
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="diasTurnos")
    public Set<AsigTurnos> getAsigTurnoses() {
        return this.asigTurnoses;
    }
    
    public void setAsigTurnoses(Set<AsigTurnos> asigTurnoses) {
        this.asigTurnoses = asigTurnoses;
    }




}


