package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Encargados generated by hbm2java
 */
@Entity
@Table(name="encargados"
    ,catalog="hospitalbd"
)
public class Encargados  implements java.io.Serializable {


     private Integer idEncargado;
     private String nombreEncargado;
     private String telefono;
     private String direccion;

    public Encargados() {
    }

    public Encargados(String nombreEncargado, String telefono, String direccion) {
       this.nombreEncargado = nombreEncargado;
       this.telefono = telefono;
       this.direccion = direccion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_encargado", unique=true, nullable=false)
    public Integer getIdEncargado() {
        return this.idEncargado;
    }
    
    public void setIdEncargado(Integer idEncargado) {
        this.idEncargado = idEncargado;
    }

    
    @Column(name="nombre_encargado", nullable=false, length=50)
    public String getNombreEncargado() {
        return this.nombreEncargado;
    }
    
    public void setNombreEncargado(String nombreEncargado) {
        this.nombreEncargado = nombreEncargado;
    }

    
    @Column(name="telefono", nullable=false, length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", nullable=false)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


