package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Horarios generated by hbm2java
 */
@Entity
@Table(name="horarios"
    ,catalog="hospitalbd"
)
public class Horarios  implements java.io.Serializable {


     private String idHorario;
     private String horario;
     private Set<AsigTurnos> asigTurnoses = new HashSet<AsigTurnos>(0);

    public Horarios() {
    }

	
    public Horarios(String idHorario, String horario) {
        this.idHorario = idHorario;
        this.horario = horario;
    }
    public Horarios(String idHorario, String horario, Set<AsigTurnos> asigTurnoses) {
       this.idHorario = idHorario;
       this.horario = horario;
       this.asigTurnoses = asigTurnoses;
    }
   
     @Id 

    
    @Column(name="id_horario", unique=true, nullable=false, length=5)
    public String getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(String idHorario) {
        this.idHorario = idHorario;
    }

    
    @Column(name="horario", nullable=false, length=50)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="horarios")
    public Set<AsigTurnos> getAsigTurnoses() {
        return this.asigTurnoses;
    }
    
    public void setAsigTurnoses(Set<AsigTurnos> asigTurnoses) {
        this.asigTurnoses = asigTurnoses;
    }




}


