package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instituciones generated by hbm2java
 */
@Entity
@Table(name="instituciones"
    ,catalog="hospitalbd"
)
public class Instituciones  implements java.io.Serializable {


     private Integer idInstitucion;
     private String institucion;
     private Set<AsigInstitucion> asigInstitucions = new HashSet<AsigInstitucion>(0);

    public Instituciones() {
    }

	
    public Instituciones(String institucion) {
        this.institucion = institucion;
    }
    public Instituciones(String institucion, Set<AsigInstitucion> asigInstitucions) {
       this.institucion = institucion;
       this.asigInstitucions = asigInstitucions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_institucion", unique=true, nullable=false)
    public Integer getIdInstitucion() {
        return this.idInstitucion;
    }
    
    public void setIdInstitucion(Integer idInstitucion) {
        this.idInstitucion = idInstitucion;
    }

    
    @Column(name="institucion", nullable=false)
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="instituciones")
    public Set<AsigInstitucion> getAsigInstitucions() {
        return this.asigInstitucions;
    }
    
    public void setAsigInstitucions(Set<AsigInstitucion> asigInstitucions) {
        this.asigInstitucions = asigInstitucions;
    }




}


