package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medicamentos generated by hbm2java
 */
@Entity
@Table(name="medicamentos"
    ,catalog="hospitalbd"
)
public class Medicamentos  implements java.io.Serializable {


     private String idMedicamento;
     private String medicamento;
     private Set<RecetasPacientes> recetasPacienteses = new HashSet<RecetasPacientes>(0);

    public Medicamentos() {
    }

	
    public Medicamentos(String idMedicamento, String medicamento) {
        this.idMedicamento = idMedicamento;
        this.medicamento = medicamento;
    }
    public Medicamentos(String idMedicamento, String medicamento, Set<RecetasPacientes> recetasPacienteses) {
       this.idMedicamento = idMedicamento;
       this.medicamento = medicamento;
       this.recetasPacienteses = recetasPacienteses;
    }
   
     @Id 

    
    @Column(name="id_medicamento", unique=true, nullable=false, length=5)
    public String getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(String idMedicamento) {
        this.idMedicamento = idMedicamento;
    }

    
    @Column(name="medicamento", nullable=false)
    public String getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentos")
    public Set<RecetasPacientes> getRecetasPacienteses() {
        return this.recetasPacienteses;
    }
    
    public void setRecetasPacienteses(Set<RecetasPacientes> recetasPacienteses) {
        this.recetasPacienteses = recetasPacienteses;
    }




}


