package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nacionalidades generated by hbm2java
 */
@Entity
@Table(name="nacionalidades"
    ,catalog="hospitalbd"
)
public class Nacionalidades  implements java.io.Serializable {


     private Integer idNacionalidad;
     private String nacionalidad;
     private Set<Registros> registroses = new HashSet<Registros>(0);

    public Nacionalidades() {
    }

    public Nacionalidades(String nacionalidad, Set<Registros> registroses) {
       this.nacionalidad = nacionalidad;
       this.registroses = registroses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_nacionalidad", unique=true, nullable=false)
    public Integer getIdNacionalidad() {
        return this.idNacionalidad;
    }
    
    public void setIdNacionalidad(Integer idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }

    
    @Column(name="nacionalidad", length=50)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nacionalidades")
    public Set<Registros> getRegistroses() {
        return this.registroses;
    }
    
    public void setRegistroses(Set<Registros> registroses) {
        this.registroses = registroses;
    }




}


