package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfiles generated by hbm2java
 */
@Entity
@Table(name="perfiles"
    ,catalog="hospitalbd"
)
public class Perfiles  implements java.io.Serializable {


     private Integer idPerfil;
     private String perfil;
     private Set<AsigPerfil> asigPerfils = new HashSet<AsigPerfil>(0);

    public Perfiles() {
    }

	
    public Perfiles(String perfil) {
        this.perfil = perfil;
    }
    public Perfiles(String perfil, Set<AsigPerfil> asigPerfils) {
       this.perfil = perfil;
       this.asigPerfils = asigPerfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_perfil", unique=true, nullable=false)
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    
    @Column(name="perfil", nullable=false, length=50)
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perfiles")
    public Set<AsigPerfil> getAsigPerfils() {
        return this.asigPerfils;
    }
    
    public void setAsigPerfils(Set<AsigPerfil> asigPerfils) {
        this.asigPerfils = asigPerfils;
    }




}


