package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Registros generated by hbm2java
 */
@Entity
@Table(name="registros"
    ,catalog="hospitalbd"
)
public class Registros  implements java.io.Serializable {


     private String idRegistro;
     private Nacionalidades nacionalidades;
     private TiposDoctores tiposDoctores;
     private String nombre;
     private String apellido;
     private char genero;
     private String edad;
     private String direccion;
     private String telefono;
     private String email;
     private String jvpm;
     private Set<AsigConsultorio> asigConsultorios = new HashSet<AsigConsultorio>(0);
     private Set<AsigPerfil> asigPerfils = new HashSet<AsigPerfil>(0);
     private Set<AsigEspecialidad> asigEspecialidads = new HashSet<AsigEspecialidad>(0);
     private Set<AsigDocumentos> asigDocumentoses = new HashSet<AsigDocumentos>(0);
     private Set<AsigTurnos> asigTurnoses = new HashSet<AsigTurnos>(0);
     private Set<AsigInstitucion> asigInstitucions = new HashSet<AsigInstitucion>(0);
     private Set<Citas> citases = new HashSet<Citas>(0);

    public Registros() {
    }

	
    public Registros(String idRegistro, Nacionalidades nacionalidades, String nombre, String apellido, char genero, String edad, String direccion, String telefono, String email) {
        this.idRegistro = idRegistro;
        this.nacionalidades = nacionalidades;
        this.nombre = nombre;
        this.apellido = apellido;
        this.genero = genero;
        this.edad = edad;
        this.direccion = direccion;
        this.telefono = telefono;
        this.email = email;
    }
    public Registros(String idRegistro, Nacionalidades nacionalidades, TiposDoctores tiposDoctores, String nombre, String apellido, char genero, String edad, String direccion, String telefono, String email, String jvpm, Set<AsigConsultorio> asigConsultorios, Set<AsigPerfil> asigPerfils, Set<AsigEspecialidad> asigEspecialidads, Set<AsigDocumentos> asigDocumentoses, Set<AsigTurnos> asigTurnoses, Set<AsigInstitucion> asigInstitucions, Set<Citas> citases) {
       this.idRegistro = idRegistro;
       this.nacionalidades = nacionalidades;
       this.tiposDoctores = tiposDoctores;
       this.nombre = nombre;
       this.apellido = apellido;
       this.genero = genero;
       this.edad = edad;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.jvpm = jvpm;
       this.asigConsultorios = asigConsultorios;
       this.asigPerfils = asigPerfils;
       this.asigEspecialidads = asigEspecialidads;
       this.asigDocumentoses = asigDocumentoses;
       this.asigTurnoses = asigTurnoses;
       this.asigInstitucions = asigInstitucions;
       this.citases = citases;
    }
   
     @Id 

    
    @Column(name="id_registro", unique=true, nullable=false, length=10)
    public String getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(String idRegistro) {
        this.idRegistro = idRegistro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nacionalidad", nullable=false)
    public Nacionalidades getNacionalidades() {
        return this.nacionalidades;
    }
    
    public void setNacionalidades(Nacionalidades nacionalidades) {
        this.nacionalidades = nacionalidades;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_dr")
    public TiposDoctores getTiposDoctores() {
        return this.tiposDoctores;
    }
    
    public void setTiposDoctores(TiposDoctores tiposDoctores) {
        this.tiposDoctores = tiposDoctores;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=50)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="genero", nullable=false, length=1)
    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }

    
    @Column(name="edad", nullable=false, length=2)
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }

    
    @Column(name="direccion", nullable=false)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false, length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="jvpm", length=6)
    public String getJvpm() {
        return this.jvpm;
    }
    
    public void setJvpm(String jvpm) {
        this.jvpm = jvpm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registros")
    public Set<AsigConsultorio> getAsigConsultorios() {
        return this.asigConsultorios;
    }
    
    public void setAsigConsultorios(Set<AsigConsultorio> asigConsultorios) {
        this.asigConsultorios = asigConsultorios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registros")
    public Set<AsigPerfil> getAsigPerfils() {
        return this.asigPerfils;
    }
    
    public void setAsigPerfils(Set<AsigPerfil> asigPerfils) {
        this.asigPerfils = asigPerfils;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registros")
    public Set<AsigEspecialidad> getAsigEspecialidads() {
        return this.asigEspecialidads;
    }
    
    public void setAsigEspecialidads(Set<AsigEspecialidad> asigEspecialidads) {
        this.asigEspecialidads = asigEspecialidads;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registros")
    public Set<AsigDocumentos> getAsigDocumentoses() {
        return this.asigDocumentoses;
    }
    
    public void setAsigDocumentoses(Set<AsigDocumentos> asigDocumentoses) {
        this.asigDocumentoses = asigDocumentoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registros")
    public Set<AsigTurnos> getAsigTurnoses() {
        return this.asigTurnoses;
    }
    
    public void setAsigTurnoses(Set<AsigTurnos> asigTurnoses) {
        this.asigTurnoses = asigTurnoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registros")
    public Set<AsigInstitucion> getAsigInstitucions() {
        return this.asigInstitucions;
    }
    
    public void setAsigInstitucions(Set<AsigInstitucion> asigInstitucions) {
        this.asigInstitucions = asigInstitucions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registros")
    public Set<Citas> getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set<Citas> citases) {
        this.citases = citases;
    }




}


