package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposExamenes generated by hbm2java
 */
@Entity
@Table(name="tipos_examenes"
    ,catalog="hospitalbd"
)
public class TiposExamenes  implements java.io.Serializable {


     private Integer idTipoExm;
     private String tipoExm;
     private Set<ExamenesPacientes> examenesPacienteses = new HashSet<ExamenesPacientes>(0);

    public TiposExamenes() {
    }

	
    public TiposExamenes(String tipoExm) {
        this.tipoExm = tipoExm;
    }
    public TiposExamenes(String tipoExm, Set<ExamenesPacientes> examenesPacienteses) {
       this.tipoExm = tipoExm;
       this.examenesPacienteses = examenesPacienteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_exm", unique=true, nullable=false)
    public Integer getIdTipoExm() {
        return this.idTipoExm;
    }
    
    public void setIdTipoExm(Integer idTipoExm) {
        this.idTipoExm = idTipoExm;
    }

    
    @Column(name="tipo_exm", nullable=false, length=50)
    public String getTipoExm() {
        return this.tipoExm;
    }
    
    public void setTipoExm(String tipoExm) {
        this.tipoExm = tipoExm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposExamenes")
    public Set<ExamenesPacientes> getExamenesPacienteses() {
        return this.examenesPacienteses;
    }
    
    public void setExamenesPacienteses(Set<ExamenesPacientes> examenesPacienteses) {
        this.examenesPacienteses = examenesPacienteses;
    }




}


