package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposDocumentos generated by hbm2java
 */
@Entity
@Table(name="tipos_documentos"
    ,catalog="hospitalbd"
)
public class TiposDocumentos  implements java.io.Serializable {


     private Integer idTipoDocu;
     private String documento;
     private Set<AsigDocumentos> asigDocumentoses = new HashSet<AsigDocumentos>(0);

    public TiposDocumentos() {
    }

	
    public TiposDocumentos(String documento) {
        this.documento = documento;
    }
    public TiposDocumentos(String documento, Set<AsigDocumentos> asigDocumentoses) {
       this.documento = documento;
       this.asigDocumentoses = asigDocumentoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_docu", unique=true, nullable=false)
    public Integer getIdTipoDocu() {
        return this.idTipoDocu;
    }
    
    public void setIdTipoDocu(Integer idTipoDocu) {
        this.idTipoDocu = idTipoDocu;
    }

    
    @Column(name="documento", nullable=false, length=50)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposDocumentos")
    public Set<AsigDocumentos> getAsigDocumentoses() {
        return this.asigDocumentoses;
    }
    
    public void setAsigDocumentoses(Set<AsigDocumentos> asigDocumentoses) {
        this.asigDocumentoses = asigDocumentoses;
    }




}


