package sv.edu.usam.www.entities;
// Generated 09-dic-2020 23:14:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="hospitalbd"
)
public class Usuarios  implements java.io.Serializable {


     private Integer idUsu;
     private Roles roles;
     private String usuario;
     private String pass;
     private Date fechaCreacion;
     private Set<Asistencias> asistenciases = new HashSet<Asistencias>(0);

    public Usuarios() {
    }

	
    public Usuarios(Roles roles, String usuario, String pass, Date fechaCreacion) {
        this.roles = roles;
        this.usuario = usuario;
        this.pass = pass;
        this.fechaCreacion = fechaCreacion;
    }
    public Usuarios(Roles roles, String usuario, String pass, Date fechaCreacion, Set<Asistencias> asistenciases) {
       this.roles = roles;
       this.usuario = usuario;
       this.pass = pass;
       this.fechaCreacion = fechaCreacion;
       this.asistenciases = asistenciases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usu", unique=true, nullable=false)
    public Integer getIdUsu() {
        return this.idUsu;
    }
    
    public void setIdUsu(Integer idUsu) {
        this.idUsu = idUsu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol", nullable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    
    @Column(name="usuario", nullable=false, length=20)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="pass", nullable=false, length=100)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Asistencias> getAsistenciases() {
        return this.asistenciases;
    }
    
    public void setAsistenciases(Set<Asistencias> asistenciases) {
        this.asistenciases = asistenciases;
    }




}


